# Generated by Django 4.2.29 on 2026-05-23 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_add_want_to_see'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='want_to_see',
        ),
    ]
