# Generated by Django 4.2.29 on 2026-05-23 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_want_record_browse_history'),
        ('users', '0003_remove_want_m2m'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='want_to_see',
            field=models.ManyToManyField(blank=True, related_name='interested_users', through='movies.WantRecord', to='movies.movie'),
        ),
    ]
