# Generated by Django 6.0.4 on 2026-05-19 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='actors/')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('poster', models.ImageField(upload_to='movies/')),
                ('score', models.FloatField(default=0)),
                ('duration', models.IntegerField()),
                ('release_time', models.DateField()),
                ('status', models.CharField(choices=[('hot', '热映'), ('coming', '即将上映'), ('offline', '已下架')], default='coming', max_length=20)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('actors', models.ManyToManyField(related_name='movies', to='movies.actor')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movies', to='movies.category')),
            ],
        ),
    ]
