# Generated by Django 6.0.4 on 2026-05-20 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_cinema_remove_hall_name_hall_cinema'),
    ]

    operations = [
        migrations.AddField(
            model_name='hall',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
