# Generated by Django 4.2.29 on 2026-05-21 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_category_to_manytomany'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Actor',
        ),
    ]
